obj-$(CONFIG_FIH_BINF) += fih_binf.o
obj-$(CONFIG_FIH_CPU) += fih_cpu.o
obj-$(CONFIG_FIH_DDR) += fih_ddr.o
obj-$(CONFIG_FIH_EXP) += fih_exp.o
obj-$(CONFIG_FIH_INFO) += fih_info.o
obj-$(CONFIG_FIH_MFD) += fih_mfd.o
obj-$(CONFIG_FIH_PDD) += fih_pdd.o
obj-$(CONFIG_FIH_SEB) += fih_seb.o
obj-$(CONFIG_FIH_SIM) += fih_sim.o
obj-$(CONFIG_FIH_TOUCH) += fih_touch.o
obj-$(CONFIG_FIH_TRAY) += fih_tray.o

